name: clima
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^3.1.0
  geolocator: ^9.0.2
  latlong2: ^0.8.1
  permission_handler: ^11.0.1
  weather: ^2.0.0
  intl: ^0.18.1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  animated_floating_buttons: ^0.0.2
  flutter_slider_drawer: ^2.1.3
  http: ^0.13.1
  geocoding: ^2.0.1
  sqflite: ^2.3.0
  path_provider: ^2.1.1
  material_text_fields: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - images/